# Generated by Django 4.2.7 on 2023-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_tickets_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='status',
        ),
        migrations.AddField(
            model_name='supporter',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of tickets'),
        ),
    ]
