# Generated by Django 4.2.7 on 2024-02-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_supporter_status_supporter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='response',
            field=models.TextField(default='The ticket is pending...', max_length=2048, verbose_name='Supporter response'),
        ),
    ]
